### ISSUE TITLE
Playback stops prematurely

### ISSUE THREAD

**Issue by wenzhang-wrnch** [eavesdrop/eavesdrop.io#10]
When I'm eavesdropping on a user, playback stops after 5-10 seconds. It will start playing again when the eavesdroppee changes songs, but it will stop again after a few seconds. I am using Chrome for Windows, and I see the following messages in the JS console:

[Tue Dec 18 2012 11:19:09 GMT-0500 (Eastern Standard Time)] >> triggered Wen eavesdropOn Andrew application-00884d4235a414246bc7144eac75407b.js:1
playback:stop application-00884d4235a414246bc7144eac75407b.js:1
[Tue Dec 18 2012 11:19:10 GMT-0500 (Eastern Standard Time)] >> song changed application-00884d4235a414246bc7144eac75407b.js:1
playback:play application-00884d4235a414246bc7144eac75407b.js:1
player.loadeddata: 681.000ms core.api-iframe.af6c779dd9d5d76b1fa72669cb5bc04c.js:667
playback:stop application-00884d4235a414246bc7144eac75407b.js:1
[Tue Dec 18 2012 11:20:35 GMT-0500 (Eastern Standard Time)] >> song changed application-00884d4235a414246bc7144eac75407b.js:1
playback:play application-00884d4235a414246bc7144eac75407b.js:1
player.loadeddata: 688.000ms core.api-iframe.af6c779dd9d5d76b1fa72669cb5bc04c.js:667
playback:stop 

It seems like only a few seconds of each song gets loaded.

**Comment by elskwid** [comment]
@spoonymushroom There's a new version now. [ALMOST THREE YEARS LATER.](http://eavesdrop.io/). I'll close this for now.
