### ISSUE TITLE
Chrome doesn't show friends' links

### ISSUE THREAD

**Issue by fnog** [eavesdrop/eavesdrop.io#11]
Tried on google chrome and no links show up when overing someone's avatar.
On the other hand, firefox show a blue clickable icon that allows me to follow someone's music.

**Comment by elskwid** [comment]
@fnog, Can you tell me what version of Chrome you're using? Thanks!

**Comment by fnog** [comment]
Hi there,

Google-chrome (linux) Version 31.0.1650.63
No image when the mouse is over the silhuete and no blue icon.

Thanks,

Francisco

**Comment by elskwid** [comment]
@fnog been a while, eh? Well I've pushed up a brand [new version](http://eavesdrop.io/). I'll close this for now. Feel free to open if you still have trouble.
