### ISSUE TITLE
Playback stops early

### ISSUE THREAD

**Issue by ghost** [eavesdrop/eavesdrop.io#12]
When listening to someone else play the song stops early, usually within 30 seconds. Have tried from IE, Firefox, Chrome (desktop/android), LG G3 default browser, and iPhone 4s. Each time the song stops within the first 30 seconds and does not restart.

**Comment by elskwid** [comment]
Thank you for the report! I will take a look tomorrow.

**Comment by ghost** [comment]
Something I forgot to mention, the broadcast account is a subscriber. The listening account is still a free account.

**Comment by elskwid** [comment]
@aenyan I've just pushed a new version to http://eavesdrop.io/. It's likely the free account will still cause you some trouble. I plan to work on at least handling the free accounts in a smart way in the next few days.
