### ISSUE TITLE
getFollowing failure

### ISSUE THREAD

**Issue by jzting** [eavesdrop/eavesdrop.io#2]
I keep getting the following error in the console:

 getFollowing failure > retry in 5 seconds

**Comment by elskwid** [comment]
@jzting - Thanks for letting us know about the problem. We've been watching the Rdio API for the last few days and it's having some issues. The trick for eavesdrop is that while we usually get all the following users it's no good for us if we don't also get the song information. We've pushed out some updates tonight to help with messaging and not keeping you in the dark as much. We'll let you know if we find something big that fixes this up.

**Comment by elskwid** [comment]
@jzting - Rdio did some work on their API service over the weekend and we're seeing dramatically improved response times and reliability. Care to give it a try today? One our devs (@sean-j-williamson, is playing some stuff today at http://eavesdrop.io/supernullset).

**Comment by jzting** [comment]
Sorry missed this update. Working now, thanks!
