### ISSUE TITLE
Can't get in?

### ISSUE THREAD

**Issue by saltydressage** [eavesdrop/eavesdrop.io#4]
Great concept.  Would love to use it.

I try to log in with Rdio .  It opens a window, and that window stays empty forever.   I'm already logged into Rdio and listening to music.

Chrome Version 23.0.1271.91 m

**Comment by coryschadt** [comment]
Same thing happened to me. I just kept on refreshing and it finally worked

**Comment by elskwid** [comment]
@jeffes, @coryschadt - We've pushed out some updates tonight that should help with the routing in the application. I'm not sure if they will solve your problems but please do give it a shot and let me know. I'd love to follow up if we're still seeing issues.

Thanks!

**Comment by saltydressage** [comment]
Closer :)  I can get a grid view of my friends now, and I believe I can see
which are online.  Although clicking on one of them, or the little speaker
on them, does nothing.  Rdio is open in a tab already.

**Comment by elskwid** [comment]
@jeffes - You can open the developer console and see what it has to say. We've been seeing some trouble with getting the list of people but the music information is wonky. We hand the playback off to rdio pretty early in the process - basically as soon as you click the eavesdrop glyph. LET'S DEBUG THIS THING! :dancers:

**Comment by elskwid** [comment]
So, almost 3 years have gone by. I just released a [new version](http://eavesdrop.io/). If you still have any interest, take a look. Take care!
