### ISSUE TITLE
Persistent 401 errors

### ISSUE THREAD

**Issue by elskwid** [eavesdrop/eavesdrop.io#5]
Several users are complaining that no matter what URL they visit they get 401 errors in the console.

**Comment by balanceiskey** [comment]
Hola Amigos,

Here are a few more details:
- Jams on this page: 

![Screenshot](https://www.evernote.com/shard/s1/sh/d45258a1-e047-481d-9c53-12fe13b3e46c/8198765c204df14e3e33e808fb84d98e/res/86aad2d7-1ff4-4cfc-80e2-521f6e21b9a3/skitch.png)
- On inspecting the console it looks like it's 401ing when hitting the rdio API

![Screenshot](https://www.evernote.com/shard/s1/sh/1186484c-b18c-48b1-ad16-b553a7c14ee7/9c81596fdb8680d43be17ebebc744b2e/res/7083e8c5-df98-4bdf-8451-12683f35c63c/skitch.png)

![Screenshot](https://www.evernote.com/shard/s1/sh/00f98cc8-d3b6-4993-9912-1264a58b0809/95331e01f1a8f50e511efa86b2cfee32/res/6c62213f-465d-4209-8ac7-ff559f872db0/skitch.png)

Not sure what access token it's using there as I'm not signed in.

**Comment by perez-rich** [comment]
I'm getting the same exact issues. Even if I try to go to a user's page I get redirected back to /signin

**Comment by just2jays** [comment]
Yeeeep, same here

**Comment by elskwid** [comment]
Ohhhh! Good catch gents. The secret is that line in the 401 messages where the log says ">> let's eavesdrop on signing". We've got a route that is falling through incorrectly. I'm on it! :running:

**Comment by balanceiskey** [comment]
Looks like it's working now! Nice :)

**Comment by elskwid** [comment]
Wouldn't have found it so soon without your investigative work and great write-up. Thanks! Closing this one down.
