### ISSUE TITLE
getFollowing Failure after Rdio API fixes (1 Dec 2012)

### ISSUE THREAD

**Issue by elskwid** [eavesdrop/eavesdrop.io#8]
A few of our users are still seeing the getFollowing error. 

`getFollowing` is an internal function eavesdrop uses to call `http://rdio.com/api/1/userFollowing`. The frequency of this error was much greater prior to the work Rdio did on the API over the weekend. Since this is really a client library we'll need to figure out if there is something happening on a particular client.

reported by: @manikrathee

**Comment by elskwid** [comment]
If possible it would be great to know a couple of things for this issue. 
1. The URL that you're trying to hit
2. The console results
3. The actual results from the `userFollowing` call

Happy to help you get any of those, although from the screenshots it looks like you know your way around a chrome console. :smile:

**Comment by manikrathee** [comment]
Hey guys.

Some extra details:
Chrome 24.0.1312.32

Happens after browser restart in regular & incognito window
Rdio is logged in but not open
Rdio DOES play when I load it in the same window instance that eavesdrop is having trouble in

Screen of console:
http://share.manikrathee.com/text/0e0a1c3w1i37

**Comment by manikrathee** [comment]
URL: http://eavesdrop.io/
(logged in, trying to see friends list to choose someone to stalk)

Console results: http://share.manikrathee.com/text/12142Y2V1s3L
Object: http://share.manikrathee.com/text/2P330m0X2416

**Comment by elskwid** [comment]
@manikrathee - eavesdrop can't actually use the pubsub (rdio is working on it). I'm more interested in the results of `userFollowing` it should JSON that looks something like:

`{"status": "ok", "result": [{"username": …`

**Comment by elskwid** [comment]
By way of "trying everything I can think of" perhaps a quick logout and login on Rdio will help. 
1. hit http://rdio.com/signout
2. Go back to eavesdrop and log in

**Comment by manikrathee** [comment]
@elskwid The incognito window essentially simulates that log out/in process, but I did it in a standard window just now anyway so we could rule it out. Issue persisted.

I don't think the userFollowing object is loading. I see Join and connectionJoin a few times then it starts the getFollowing loop.

http://share.manikrathee.com/text/3X2H2x2U0O0x

**Comment by elskwid** [comment]
In the Developer Tools pane there is a Network section(tab). Under there you should see some resource, either local to eavesdrop, or from rdio, that is failing on you. Probably highlighted in red. Can I see what that is and if it is an rdio resource perhaps some details on the response.

Also, thanks a lot for doing this!

**Comment by manikrathee** [comment]
userFollowing is showing a 200 - there are 8 instances of it, with a new one being added every 10~ seconds.

However, the preview headers for all of them show this: http://share.manikrathee.com/image/0j41430w453P

http://share.manikrathee.com/image/0j41430w453P

The rdio help is throwing a 304: http://share.manikrathee.com/text/323a3C1U2v0c / but everything else is 200

**Comment by manikrathee** [comment]
Response header for userFollowing: http://share.manikrathee.com/text/1k1h1T2h0G1C

**Comment by elskwid** [comment]
@manikrathee Excellent work. Check out that first person. `misspearlman`. For some reason her `lastSongPlayed` info is `null` and it just so happens that we just check the first result to see if song info is coming back. We haven't seen a result like this where some users have song info and some don't. 

I'm on it.

**Comment by manikrathee** [comment]
She just joined and i'm pretty sure she hasn't played anything yet so her account is barren. 

Let me know if you need any other info when you get that straightened out.

**Comment by elskwid** [comment]
Perfect. Great to know!

**Comment by manikrathee** [comment]
@elskwid  one option is that it might be better to check if lastSongPlayed is coming back at all, regardless of the content. 

If there is an error with request, you wouldn't be getting any JSON back and lastSongPlayed wouldn't exist. That would solve the issue of users without any play data.

**Comment by elskwid** [comment]
@manikrathee - you'd think so but rdio has API problems for the last few weeks (right after we built this) where the portion of their service that populated the lastSongPlayed information was degrading. We'd get a list but no song information, which is kind of important for us. Ha.

**Comment by manikrathee** [comment]
@elskwid well that's counterproductive.

**Comment by elskwid** [comment]
:+1:

**Comment by elskwid** [comment]
Hey @manikrathee, let me know if you're good to go now.

**Comment by manikrathee** [comment]
bingo - all good over here.

---

Manik Rathee
User Experience Engineer, Obama For America
www.barackobama.com
@manikrathee

**Comment by elskwid** [comment]
:sparkler:

**Comment by elskwid** [comment]
Excellent news.

**Comment by elskwid** [comment]
Just to close this out - new users have empty song info, which makes sense. Our `getFollowing` call was naively checking the first result to verify if song information was returned. If you had just followed a new user then they would be your first result and we would see no song info and then assume all song info for all results must be missing. 

I've updated this bit of Eavesdrop to be smarter and look for _any_ song info and punting the problem down to our `isActive` stuff. Now the new user is displayed, greyed out with missing album artwork. 

Thanks again @manikrathee.

**Comment by manikrathee** [comment]
Happy to help @elskwid
